language: c
sudo: false

addons:
    apt:
        packages:
            - doxygen

install:
    - export BOARD="$B" && echo "BOARD='$BOARD'"
    - export TARGETS="$T" && echo "TARGETS='$TARGETS'"
    - make conda
    - export PATH=$PWD/conda/bin:$PATH
    - which sdcc
    - sdcc --version
    - ./.travis/setup.sh

script:
    - make $TARGETS

jobs:
    fail_fast: true
    include:
        #-----------------------------------------
        # HDMI2USB targets
        #-----------------------------------------
        - stage: Build
          env: B=opsis T="firmware-fx2"
        - stage: Build
          env: B=atlys T="firmware-fx2"

        #-----------------------------------------
        # Unconfigured targets
        #-----------------------------------------
        - stage: Build
          env: B=opsis T="firmware-unconfigured"
        - stage: Build
          env: B=atlys T="firmware-unconfigured"

        #-----------------------------------------
        # Build and deploy docs
        #-----------------------------------------
        - stage: Deploy docs
          script:
              - make docs
              - ./.travis/push-docs.sh
