language: c
sudo: false

addons:
    apt:
        packages:
            - doxygen

install:
    - export BOARD="$B" && echo "BOARD='$BOARD'"
    - export DIR="$D" && echo "DIR='$DIR'"
    - make conda
    - export PATH=$PWD/conda/bin:$PATH
    - which sdcc
    - sdcc --version
    - ./.travis/setup.sh

script:
    - make -C $DIR

jobs:
    fail_fast: true
    include:
        #-----------------------------------------
        # cdc-loopback
        #-----------------------------------------
        - stage: Build
          env: B=opsis D="examples/cdc-loopback"
        - stage: Build
          env: B=atlys D="examples/cdc-loopback"

        #-----------------------------------------
        # serial-loopback
        #-----------------------------------------
        - stage: Build
          env: B=opsis D="examples/serial-loopback"
        - stage: Build
          env: B=atlys D="examples/serial-loopback"

        #-----------------------------------------
        # serial-cdc-loopback
        #-----------------------------------------
        - stage: Build
          env: B=opsis D="examples/serial-cdc-loopback"
        - stage: Build
          env: B=atlys D="examples/serial-cdc-loopback"

        #-----------------------------------------
        # Build and deploy docs
        #-----------------------------------------
        - stage: Deploy docs
          script:
              - make docs
              - ./.travis/push-docs.sh
