TARGET    = hdmi2usb
LIBRARIES = fx2 fx2usb fx2isrs
FLAGS     = -I../common -DDEBUG
SOURCES   = main descriptors dna \
			../common/cdc \
			../common/uac \
			../common/uvc \
			../common/uart

include ../common/common.mk
