#
# Copyright (C) 2009-2012 Chris McClelland
# Copyright (C) 2015 Joel Stanley <joel@jms.id.au>
# Copyright (C) 2017 Kyle Robbertze <krobbertze@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# To build the firmware you will need:
#   SDCC from http://sdcc.sourceforge.net
#   fx2lib from http://fx2lib.wiki.sourceforge.net
#
TARGET := lights
FX2LIBDIR := ../../third_party/fx2lib
GITMODULESDIR := ../../.gitmodules
BOARD ?= fx2

CC_SRCS := lights.c

include ../common.mk
