TARGET    = serial-bitbang
LIBFX2DIR = ../../third_party/libfx2
LIBRARIES = fx2 fx2usb fx2isrs
FLAGS     = -I../../common -DDEBUG
SOURCES   = main descriptors ../../common/cdc ../../common/uart

include ../../common/common.mk
